apiVersion: v1
kind: ConfigMap
data:
  nginx.conf: |
    server {
            listen 80 default_server;

            root /usr/share/nginx/html;
            index index.html;

            server_name my-website.com;

            location / {
                    try_files $uri $uri/ =404;
            }
    }
metadata:
  name: nginxconfigmap
---
apiVersion: v1
kind: Service
metadata:
  name: vault-agent-janapp
  labels:
    run: vault-agent-janapp
spec:
  type: NodePort
  selector:
    run: vault-agent-janapp
  ports:
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 32080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent-janapp
spec:
  selector:
    matchLabels:
      run: vault-agent-janapp
  replicas: 2
  template:
    metadata:
      labels:
        run: vault-agent-janapp
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "janapp-role"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-run-as-same-user: "true"
        vault.hashicorp.com/agent-set-security-context: "true"
        vault.hashicorp.com/agent-cache-enable: "true"
        vault.hashicorp.com/namespace: "sea"
        # Static secret as index.html
        vault.hashicorp.com/secret-volume-path-sea.html: "/usr/share/nginx/html"
        vault.hashicorp.com/agent-inject-secret-sea.html: "secret/sea"
        vault.hashicorp.com/agent-inject-template-sea.html: |
          {{- with secret "secret/sea" -}}
          {{ .Data.value }}
          {{- end }}
        # Static secret as sa.html
        vault.hashicorp.com/secret-volume-path-sa.html: "/usr/share/nginx/html"
        vault.hashicorp.com/agent-inject-secret-sa.html: "sa/secret/sa-team-secret"
        vault.hashicorp.com/agent-inject-template-sa.html: |
          {{- with secret "sa/secret/sa-team-secret" -}}
          {{ .Data.value }}
          {{- end }}
        # Static secret as janapp.html
        vault.hashicorp.com/secret-volume-path-janapp.html: "/usr/share/nginx/html"
        vault.hashicorp.com/agent-inject-secret-janapp.html: "sa/secret/sa-app-secrets/janapp"
        vault.hashicorp.com/agent-inject-template-janapp.html: |
          {{- with secret "sa/secret/sa-app-secrets/janapp" -}}
          {{ .Data.value }}
          {{- end }}
    spec:
      volumes:
      - name: configmap-volume
        configMap:
          name: nginxconfigmap
      securityContext:
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "80"
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged
        securityContext:
          runAsUser: 1000570000
          runAsGroup: 1000
        ports:
          - containerPort: 80
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        livenessProbe:
          httpGet:
            path: /sea.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
      shareProcessNamespace: true
      serviceAccountName: vault-agent-auth-janapp
---